name: Ansible Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: ansible-lint
        uses: ansible/ansible-lint-action@master
        with:
          targets: "roles/"
          args: "q"

      #- name: ansible-lint run
      #  run: ansible-lint -p roles/
      #  working-directory: /home/runner/work/ansible-lnt/ansible-lnt

