name: Ansible Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: ansible-lint
        uses: ansible/ansible-lint-action@master
        with:
          targets: roles/
        run: ansible-lint -p roles/

