name: Ansible Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Ansible Lint - Pre-Req
        run: |
          pip install ansible ansible-lint

      - name: Ansible Lint
        run: |
          ansible-lint -v --force-color roles/

      #- name: ansible-lint
      #  uses: ansible/ansible-lint-action@master
      #  with:
      #    targets: "roles/"
      #    args: "q"

      #- name: ansible-lint run
      #  run: ansible-lint -p roles/
      #  working-directory: /home/runner/work/ansible-lnt/ansible-lnt

